import { query } from 'express-validator';

export const collectionValidators = {
  getMonthlyPerformance: [
    query('group').optional().isString(),
    query('date').optional().isISO8601(),
    query('status').optional().isString(),
  ],
  getDailyPerformance: [
    query('group').optional().isString(),
    query('date').optional().isISO8601(),
    query('status').optional().isString(),
  ],
  getTeamMonthlyPerformance: [
    query('group').optional().isString(),
    query('status').optional().isString(),
  ],
  getTeamDailyPerformance: [
    query('group').optional().isString(),
    query('status').optional().isString(),
  ],
  getCollectionCase: [
    query('mobile').optional().isString(),
    query('name').optional().isString(),
    query('loanNum').optional().isString(),
    query('loanOrderNum').optional().isString(),
    query('stage').optional().isString(),
    query('collector').optional().isInt(),
    query('product').optional().isString(),
    query('loanTenure').optional().isInt(),
    query('loanAmt').optional().isDecimal(),
    query('appVersion').optional().isString(),
    query('dueDate').optional().isISO8601(),
    query('loanStatus').optional().isString(),
    query('tag').optional().isString(),
    query('repeatedBorrowing').optional().isIn(['true', 'false']),
    query('loanType').optional().isString(),
    query('result').optional().isString(),
    query('followUpDay').optional().isIn(['true', 'false']),
    query('appName').optional().isString(),
    query('proportion').optional().isDecimal(),
  ],
  getCaseAllocation: [
    query('stage').optional().isString(),
    query('collector').optional().isInt(),
    query('product').optional().isString(),
    query('userSelect').optional().isString(),
    query('numLoans').optional().isInt(),
    query('appChannel').optional().isString(),
    query('loanNum').optional().isString(),
    query('loanOrderNum').optional().isString(),
    query('repeatedBorrowing').optional().isIn(['true', 'false']),
    query('daysOverdue').optional().isInt(),
    query('mobile').optional().isString(),
    query('result').optional().isString(),
    query('largeGroup').optional().isString(),
    query('district').optional().isString(),
    query('otherStates').optional().isString(),
    query('appName').optional().isString(),
    query('dueDate').optional().isISO8601(),
  ],
  getCollectionRecords: [
    query('personnel').optional().isInt(),
    query('loanNum').optional().isString(),
    query('loanOrderNum').optional().isString(),
    query('mobile').optional().isString(),
    query('mark').optional().isString(),
    query('recordTime').optional().isISO8601(),
    query('contact').optional().isString(),
    query('targetContact').optional().isString(),
    query('connection').optional().isString(),
    query('willingnessPay').optional().isString(),
    query('overdueReason').optional().isString(),
    query('result').optional().isString(),
  ],
};
