// src/types/performance.ts
export enum PerformanceType {
  TELEMARKETER_DAILY = 'telemarketer_daily',
  TELEMARKETER_MONTHLY = 'telemarketer_monthly',
  TEAM_DAILY = 'team_daily',
  TEAM_MONTHLY = 'team_monthly',
  COLLECTOR_DAILY = 'collector_daily',
  COLLECTOR_MONTHLY = 'collector_monthly',
}

export interface Performance {
  id: number;
  user_id?: number | null;
  group_name: string;
  type: PerformanceType;
  date: string; // ISO string (YYYY-MM-DD)
  date_range?: string | null;
  ranking?: number | null;
  total_assigned_qty: number;
  new_assigned_num: number;
  target_repay_rate: number;
  target_num: number;
  num_of_apps: number;
  app_rate: number;
  num_of_approved_apps: number;
  handle_num: number;
  bonus: number;
  status: string;
  days_of_employment?: number | null;
  num_of_calls?: number | null;
  num_of_connections?: number | null;
  phone_connection_rate?: number | null;
  total_call_duration?: number | null;
  first_call_time?: string | null; // ISO string
  latest_call_time?: string | null; // ISO string
  case_coverage?: number | null;
  num_of_sms?: number | null;
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreatePerformanceInput = Omit<
  Performance,
  'id' | 'created_at' | 'updated_at'
>;
export type UpdatePerformanceInput = Partial<
  Omit<Performance, 'id' | 'created_at' | 'user_id' | 'date' | 'type'>
>;
