// src/types/transaction.ts

type State = 'SUCCESSFUL' | 'FAILED' | 'PENDING1' | 'PENDING';

export interface Transaction {
  id: number;
  transaction_id: string;
  amount: number;
  benefice: number;
  comission: number;
  destination: string;
  fee: number;
  response: string;
  error?: string;
  service_id: number;
  customer_name: string;
  state: State;
  custom_data?: string;
  ipn_url: string;
  provider_id: null;
  sms_link: number;
  ipn_state: number;
  w_amount_after_transaction: string;
  p_last_wallet_amount: number;
  p_new_wallet_amount: null;
  p_id: string;
  hash: string;
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreateTransactionInput = Omit<
  Transaction,
  'id' | 'created_at' | 'updated_at'
>;
export type UpdateTransactionInput = Partial<
  Omit<Transaction, 'id' | 'created_at'>
>;
