// src/collectionRecord.ts
export enum ConnectionStatus {
  CONNECTED = 'connected',
  NO_ANSWER = 'no_answer',
  WRONG_NUMBER = 'wrong_number',
}

export enum WillingnessToPay {
  HIGH = 'high',
  // MEDIUM = 'medium',
  // LOW = 'low',
  REFUSAL = 'refusal',
}

export interface CollectionRecord {
  id: number;
  loan_id: number;
  collector_id: number;
  mark: string;
  record_content: string;
  contact: string;
  target_contact: string;
  connection: ConnectionStatus;
  willingness_to_pay: WillingnessToPay;
  overdue_reason: string;
  result: string;
  record_time: string; // ISO string
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreateCollectionRecordInput = Omit<
  CollectionRecord,
  'id' | 'created_at' | 'updated_at'
>;
export type UpdateCollectionRecordInput = Partial<
  Omit<CollectionRecord, 'id' | 'created_at' | 'loan_id' | 'collector_id'>
>;
