// src/types/loan.ts

export enum LoanStatus {
  PENDING = 'pending',
  ACCEPTED = 'accepted',
  DENIED = 'denied',
  REPAID = 'repaid',
}

export interface Loan {
  id: number;
  loan_number: string;
  loan_order_number: string;
  product_name: string;
  customer_id: number;
  loan_amount: number;
  loan_tenure: number;
  loan_type: string;
  due_date: string; // ISO string
  app_status: string;
  app_channel: string;
  app_version: string;
  app_name: string;
  collector_id?: number | null;
  collection_stage?: string | null;
  days_overdue?: number | null;
  total_repayment: number;
  amount_repaid?: number | null;
  tag?: string | null;
  repeated_borrowing: boolean;
  loan_status: LoanStatus;
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreateLoanInput = Omit<Loan, 'id' | 'created_at' | 'updated_at'>;
export type UpdateLoanInput = Partial<
  Omit<Loan, 'id' | 'created_at' | 'loan_number' | 'customer_id'>
>;
