// src/types/marketingRecord.ts
export enum MarketingRecordRejectionIssues {
  HIGH_SERVICE_FEE = 'high_service_fee',
  SHORT_PAYMENT_DURATION = 'short_payment_duration',
  NOT_INTERESTED = 'not_interested',
  WILL_APPLY_LATER = 'will_apply_later',
}

export enum MarketingRecordReason {
  OFFLINE = 'offline',
  BUSY = 'busy',
  SHUTDOWN = 'shutdown',
}

export interface MarketingRecord {
  id: number;
  customer_id: number;
  telemarketer_id: number;
  connected: boolean;
  applying?: boolean;
  rejection_issues?: MarketingRecordRejectionIssues;
  whether_send_link?: boolean;
  remark?: string;
  reason?: MarketingRecordReason;
  created_at: string; // Auto-generated by Supabase
  updated_at: string; // Auto-generated by Supabase
}

// Types pour les opérations CRUD
export type CreateMarketingRecordInput = Omit<
  MarketingRecord,
  'id' | 'created_at' | 'updated_at'
>;
export type UpdateMarketingRecordInput = Partial<
  Omit<MarketingRecord, 'id' | 'created_at' | 'customer_id' | 'telemarketer_id'>
>;
