import { CollectionLoanProps, CollectionRecordProps } from '@cfafrica/ui';
import React from 'react';

enum KycStatus {
  PENDING = 'pending',
  SUCCESS = 'success',
  FAILED = 'failed',
}

export type Data =
  | {
      refetch(): void;
      detail: CollectionLoanProps & {
        mobile: string;
        gender: string;
        real_amount: number;
        service_fees: number;
        interest: number;
        penalty: number;
      };
      kyc: {
        id: number;
        customer_id: number;
        first_name?: string;
        last_name: string;
        location: string;
        birthdate: string;
        emergency_number_1: string;
        emergency_number_2?: string;
        front_photo: string;
        back_photo: string;
        selfie: string;
        status: KycStatus;
        created_at: string; // Auto-generated by Supabase
        updated_at: string; // Auto-generated by Supabase
      };
      mark: CollectionRecordProps[];
      canAddRemark: boolean;
      success: boolean;
    }
  | undefined;

const Context = React.createContext<Data>(undefined);

export const useCollection = () => React.useContext(Context);

export function CollectionProvider({
  children,
  ...props
}: React.PropsWithChildren<Data>) {
  return <Context.Provider value={props}>{children}</Context.Provider>;
}
